# Generated by Django 5.1 on 2024-09-17 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(blank=True, max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_comment_creator', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_comments', to='tasks.subtask')),
            ],
        ),
    ]
