# Generated by Django 5.1 on 2024-09-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_comment_comment_comment_comment_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_details',
            new_name='content',
        ),
    ]
