services:
  postgres:
    image: postgres:15
    env_file: .env
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    networks:
      - app_network

  api:
    build: .
    image: django-docker
    env_file: .env
    restart: unless-stopped
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./rclone/config:/rclone/config
    expose:
      - 80
    depends_on:
      - postgres
    networks:
      - app_network

  celery:
    container_name: worker
    build: .
    image: django-docker
    env_file: .env
    command: celery -A ManagerX-api worker -l INFO
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672/
    depends_on:
      - redis
      - rabbit
      - api
    networks:
      - app_network

  redis:
    image: redis:latest
    hostname: redis
    expose:
      - 6379

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    expose:
      - 15672
      - 5672


  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    volumes:
      - ./rclone/config:/config/rclone
      - ./rclone/logs:/logs
      - ./rclone/cache:/root/.cache/rclone # This is for the WebUI, not VFS
      - /Users/guluadim/mnt:/hostfs:shared
      - /var/cache/rclone:/vfsCache
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/fuse.conf:/etc/fuse.conf:ro
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    command:
      - rcd
      - --rc-web-gui
      - --rc-web-gui-no-open-browser
      - --rc-addr=:$RCLONE_PORT
      - --rc-user=$RCLONE_USERNAME
      - --rc-pass=$RCLONE_PASSWORD
      - --log-file=/logs/rclone.log
      - --log-level=NOTICE
      - --cache-dir=/vfsCache
    expose:
      - 5572
    environment:
      - TZ=America/New_York
    restart: unless-stopped

  rclone_initializer:
    build:
      context: ./rclone
    container_name: rclone_initializer
    env_file:
      - .env
    volumes:
      - ./rclone/mounts.json:/app/mounts.json
    restart: unless-stopped
    depends_on:
      - rclone

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app_network

volumes:
  postgres-data:
  media_volume:
  static_volume:
  portainer_data:

networks:
  app_network:
    driver: bridge
