services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ManagerX
      POSTGRES_USER: ManagerX
      POSTGRES_PASSWORD: ManagerX
    ports:
      - "5433:5432"

  api:
    container_name: ManagerX-api
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - ./media:/usr/src/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: ".env"
    environment:
      DJANGO_SETTINGS_MODULE: ManagerX-api.settings

  # Redis - result backend
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin

  celery:
    container_name: worker
    build:
      context: .
    command: celery -A ManagerX-api worker -l INFO
    volumes:
      - .:/usr/src/app/
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672/
    depends_on:
      - redis
      - rabbit
      - api

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/portainer_data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  postgres_data:
  portainer_data:
