# Generated by Django 5.1 on 2024-08-17 06:24

import apps.expertiseMainFlow.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(default='<django.db.models.fields.CharField>', max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('url', 'Url'), ('date', 'Date'), ('boolean', 'Bool'), ('integer', 'Int'), ('float', 'Float')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseFolder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('conclusionNumber', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('DONE', 'Done'), ('REJECTED', 'Rejected'), ('UNCERTAIN', 'Uncertain')], max_length=255)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_folders', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='folder_tags', to='expertiseMainFlow.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FolderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(max_length=255, null=True)),
                ('value_url', models.URLField(null=True)),
                ('value_date', models.DateField(null=True)),
                ('value_bool', models.BooleanField(null=True)),
                ('value_int', models.IntegerField(null=True)),
                ('value_float', models.FloatField(null=True)),
                ('expertise_folder', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='expertiseMainFlow.expertisefolder')),
                ('field', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='expertiseMainFlow.customfield')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.expertiseMainFlow.utils.get_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='expertiseMainFlow.expertisefolder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_files', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='file_tags', to='expertiseMainFlow.tag')),
            ],
        ),
    ]
