# Generated by Django 5.1 on 2024-09-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseMainFlow', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='file',
            name='tags',
        ),
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(default='fb11d3fe-b1cf-4ed1-a174-8e642eef9da3', on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expertisedata',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_data', to='tasks.task', unique=True),
        ),
    ]
