# Generated by Django 5.1 on 2024-09-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseMainFlow', '0002_remove_file_folder_remove_file_tags_file_task_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='task',
        ),
        migrations.AddField(
            model_name='file',
            name='subtask',
            field=models.ForeignKey(default='511ef6f1-ea6a-4ade-9427-80fa1f601b89', on_delete=django.db.models.deletion.CASCADE, related_name='subtask_files', to='tasks.subtask'),
            preserve_default=False,
        ),
    ]
