# Generated by Django 5.1 on 2024-08-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseMainFlow', '0002_sharedfolderdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFolderData',
        ),
    ]
