# Generated by Django 5.1 on 2024-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertiseMainFlow', '0003_remove_file_task_file_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisedata',
            name='conclusionNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
