services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    volumes:
      - type: bind
        source: /home/nindza/backup
        target: /hostfs
        bind:
          propagation: shared
      - ./config:/config/rclone
      - ./logs:/logs
      - ./cache:/root/.cache/rclone # This is for the WebUI, not VFS
      - /var/cache/rclone:/vfsCache
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/fuse.conf:/etc/fuse.conf:ro
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    command:
      - rcd
      - --rc-web-gui
      - --rc-web-gui-no-open-browser
      - --rc-addr=:5572
      - --rc-user=admin
      - --rc-pass=admin
      - --log-file=/logs/rclone.log
      - --log-level=NOTICE
      - --cache-dir=/vfsCache
    networks:
#      - reverse-proxy-network # Optional
      - rclone-net
    # If not using reverse proxy, provide a host:container port for --rc-addr
    ports:
      - 5572:5572
    environment:
      - TZ=America/New_York
    restart: unless-stopped

  rclone_initializer:
    build:
      context: .
    container_name: rclone_initializer
    environment:
      - RCLONE_USERNAME=admin
      - RCLONE_PASSWORD=admin
      - RCLONE_PORT=5572
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mounts.json:/app/mounts.json
    restart: unless-stopped
    depends_on:
      - rclone
    networks:
      - rclone-net

networks:
  rclone-net: